name: Build Binary

on:
  push:
    branches:
      - '*'
    tags:
      - '*'
  pull_request:

env:
  PUBLISHER_NAME: Release
  EXTENSION_ID: goreleaser

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: '17'
          cache: 'npm'
          cache-dependency-path: package-lock.json
      - run: npm install
      - run: npm run compile
      - run: npm run publish_ci
  release:
    needs: build
    runs-on: ubuntu-latest
    if: success() && startsWith(github.ref, 'refs/tags/')
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: '17'
          cache: 'npm'
          cache-dependency-path: package-lock.json
      - run: npm install
      - run: npm run create
      - name: Upload binaries to release
        uses: svenstaro/upload-release-action@v2
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          file: dist/*
          file_glob: true
          overwrite: true
          tag: ${{ github.ref }}