name: Build Binary

on:
  push:
    paths-ignore:
      - '.github/**'
      - '**/*.md'
      - 'images/**'
    branches:
      - '*'
    tags:
      - '*'
  pull_request:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@ac593985615ec2ede58e132d2e21d2b1cbd6127c # v3.3.0
      - uses: actions/setup-node@64ed1c7eab4cce3362f8c340dee64e5eaeef8f7c # v3.6.0
        with:
          node-version: '18'
          cache: 'npm'
          cache-dependency-path: package-lock.json
      - run: npm install
      - run: npm run compile
  publish-dev:
    needs: build
    runs-on: ubuntu-latest
    if: success() && startsWith(github.ref, 'refs/heads/main')
    steps:
      - uses: actions/checkout@ac593985615ec2ede58e132d2e21d2b1cbd6127c # v3.3.0
      - uses: actions/setup-node@64ed1c7eab4cce3362f8c340dee64e5eaeef8f7c # v3.6.0
        with:
          node-version: '18'
          cache: 'npm'
          cache-dependency-path: package-lock.json
      - run: npm install
      - name: get-npm-version
        id: package-version
        uses: martinbeentjes/npm-get-version-action@7aa1d82604bb2dbe377a64ca35e692e6fe333c9c # master
      - name: update version
        uses: jacobtomlinson/gha-find-replace@4d085e89079e4d2e6971679ebc87da71492aa462 # v3
        with:
          find: "extension_version"
          replace: ${{ steps.package-version.outputs.current-version}}
          include: "vss-extension.json"
      - name: update extension id
        uses: jacobtomlinson/gha-find-replace@4d085e89079e4d2e6971679ebc87da71492aa462 # v3
        with:
          find: "extension_id"
          replace: ${{ secrets.EXTENSION_DEV_ID }}
          include: "vss-extension.json"
      - name: update extension publisher
        uses: jacobtomlinson/gha-find-replace@4d085e89079e4d2e6971679ebc87da71492aa462 # v3
        with:
          find: "extension_publisher"
          replace: ${{ secrets.EXTENSION_DEV_PUBLISHER }}
          include: "vss-extension.json"
      - name: update extension public
        uses: jacobtomlinson/gha-find-replace@4d085e89079e4d2e6971679ebc87da71492aa462 # v3
        with:
          find: "extension_public"
          replace: false
          include: "vss-extension.json"
      - name: update task id
        uses: jacobtomlinson/gha-find-replace@4d085e89079e4d2e6971679ebc87da71492aa462 # v3
        with:
          find: "task_id"
          replace: ${{ secrets.TASK_DEV_ID }}
          include: "goreleaserTask/task.json"
      - run: npm run create
      - name: Upload azure devops extension to marketplace
        run: |
          export VERSION=${{ steps.package-version.outputs.current-version}}
          npm run unpublish_ci
          npm run publish_ci
          npm run share_dev
        env:
          AZURE_DEVOPS_EXT_PAT: ${{ secrets.AZURE_DEVOPS_EXT_PAT_DEV }}
          PUBLISHER_NAME: ${{ secrets.EXTENSION_DEV_PUBLISHER }}
          EXTENSION_ID: ${{ secrets.EXTENSION_DEV_ID }}
          SHARE_WITH_DEV_ORGA: ${{ secrets.SHARE_WITH_DEV_ORGA }}
  release:
    needs: build
    runs-on: ubuntu-latest
    if: success() && startsWith(github.ref, 'refs/tags/')
    steps:
      - uses: actions/checkout@ac593985615ec2ede58e132d2e21d2b1cbd6127c # v3.3.0
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
      - uses: actions/setup-node@64ed1c7eab4cce3362f8c340dee64e5eaeef8f7c # v3.6.0
        with:
          node-version: '18'
          cache: 'npm'
          cache-dependency-path: package-lock.json
      - run: npm install
      - name: get-npm-version
        id: package-version
        uses: martinbeentjes/npm-get-version-action@7aa1d82604bb2dbe377a64ca35e692e6fe333c9c # master
      - name: update version
        uses: jacobtomlinson/gha-find-replace@4d085e89079e4d2e6971679ebc87da71492aa462 # v3
        with:
          find: "extension_version"
          replace: ${{ steps.package-version.outputs.current-version}}
          include: "vss-extension.json"
      - name: update extension id
        uses: jacobtomlinson/gha-find-replace@4d085e89079e4d2e6971679ebc87da71492aa462 # v3
        with:
          find: "extension_id"
          replace: ${{ secrets.EXTENSION_PROD_ID }}
          include: "vss-extension.json"
      - name: update extension publisher
        uses: jacobtomlinson/gha-find-replace@4d085e89079e4d2e6971679ebc87da71492aa462 # v3
        with:
          find: "extension_publisher"
          replace: ${{ secrets.EXTENSION_PROD_PUBLISHER }}
          include: "vss-extension.json"
      - name: update extension public
        uses: jacobtomlinson/gha-find-replace@4d085e89079e4d2e6971679ebc87da71492aa462 # v3
        with:
          find: "extension_public"
          replace: true
          include: "vss-extension.json"
      - name: update task id
        uses: jacobtomlinson/gha-find-replace@4d085e89079e4d2e6971679ebc87da71492aa462 # v3
        with:
          find: "task_id"
          replace: ${{ secrets.TASK_PROD_ID }}
          include: "goreleaserTask/task.json"
      - run: npm run create
      - name: Upload azure devops extension to marketplace
        run: |
          export VERSION=${{ steps.package-version.outputs.current-version}}
          npm run publish_ci
        env:
          AZURE_DEVOPS_EXT_PAT: ${{ secrets.AZURE_DEVOPS_EXT_PAT }}
          PUBLISHER_NAME: ${{ secrets.EXTENSION_PROD_PUBLISHER }}
          EXTENSION_ID: ${{ secrets.EXTENSION_PROD_ID }}
      - name: Upload azure devops extension to release
        if: always()
        uses: svenstaro/upload-release-action@7319e4733ec7a184d739a6f412c40ffc339b69c7 # v2
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          file: dist/*
          file_glob: true
          overwrite: true
          tag: ${{ github.ref }}
      - run: git fetch origin main
        if: always()
      - name: 'Automated Version Bump of package.json'
        if: always()
        uses: phips28/gh-action-bump-version@25cd8ffb8ec95f16f83a8dac9557a845e4fa9e21 # master
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          skip-tag: 'true'
          target-branch: 'main'
