name: Build Binary

on:
  push:
    paths-ignore:
      - '.github/**'
      - '**/*.md'
      - 'images/**'
    branches:
      - '*'
    tags:
      - '*'
  pull_request:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@9bb56186c3b09b4f86b1c65136769dd318469633 # v4.1.2
      - uses: actions/setup-node@60edb5dd545a775178f52524783378180af0d1f8 # v4.0.2
        with:
          node-version: '18'
          cache: 'npm'
          cache-dependency-path: package-lock.json
      - run: npm install
      - run: npm run compile
  publish-dev:
    needs: build
    runs-on: ubuntu-latest
    if: success() && startsWith(github.ref, 'refs/heads/main')
    steps:
      - uses: actions/checkout@9bb56186c3b09b4f86b1c65136769dd318469633 # v4.1.2
      - uses: actions/setup-node@60edb5dd545a775178f52524783378180af0d1f8 # v4.0.2
        with:
          node-version: '18'
          cache: 'npm'
          cache-dependency-path: package-lock.json
      - run: npm install
      - name: get-npm-version
        id: package-version
        uses: martinbeentjes/npm-get-version-action@3cf273023a0dda27efcd3164bdfb51908dd46a5b # v10.1.1
      - name: update version
        uses: jacobtomlinson/gha-find-replace@a51bbcd94d000df9ca0fcb54ec8be69aad8374b0 # v3.0.2
        with:
          find: "extension_version"
          replace: ${{ steps.package-version.outputs.current-version}}
          include: "vss-extension.json"
      - name: update extension id
        uses: jacobtomlinson/gha-find-replace@a51bbcd94d000df9ca0fcb54ec8be69aad8374b0 # v3.0.2
        with:
          find: "extension_id"
          replace: ${{ secrets.EXTENSION_DEV_ID }}
          include: "vss-extension.json"
      - name: update extension publisher
        uses: jacobtomlinson/gha-find-replace@a51bbcd94d000df9ca0fcb54ec8be69aad8374b0 # v3.0.2
        with:
          find: "extension_publisher"
          replace: ${{ secrets.EXTENSION_DEV_PUBLISHER }}
          include: "vss-extension.json"
      - name: update extension public
        uses: jacobtomlinson/gha-find-replace@a51bbcd94d000df9ca0fcb54ec8be69aad8374b0 # v3.0.2
        with:
          find: "extension_public"
          replace: false
          include: "vss-extension.json"
      - name: update task id
        uses: jacobtomlinson/gha-find-replace@a51bbcd94d000df9ca0fcb54ec8be69aad8374b0 # v3.0.2
        with:
          find: "task_id"
          replace: ${{ secrets.TASK_DEV_ID }}
          include: "goreleaserTask/task.json"
      - run: npm run create
      - name: Upload azure devops extension to marketplace
        run: |
          export VERSION=${{ steps.package-version.outputs.current-version}}
          npm run unpublish_ci
          npm run publish_ci
          npm run share_dev
        env:
          AZURE_DEVOPS_EXT_PAT: ${{ secrets.AZURE_DEVOPS_EXT_PAT_DEV }}
          PUBLISHER_NAME: ${{ secrets.EXTENSION_DEV_PUBLISHER }}
          EXTENSION_ID: ${{ secrets.EXTENSION_DEV_ID }}
          SHARE_WITH_DEV_ORGA: ${{ secrets.SHARE_WITH_DEV_ORGA }}
  release:
    needs: build
    runs-on: ubuntu-latest
    if: success() && startsWith(github.ref, 'refs/tags/')
    steps:
      - uses: actions/checkout@9bb56186c3b09b4f86b1c65136769dd318469633 # v4.1.2
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
      - uses: actions/setup-node@60edb5dd545a775178f52524783378180af0d1f8 # v4.0.2
        with:
          node-version: '18'
          cache: 'npm'
          cache-dependency-path: package-lock.json
      - run: npm install
      - name: get-npm-version
        id: package-version
        uses: martinbeentjes/npm-get-version-action@3cf273023a0dda27efcd3164bdfb51908dd46a5b # v1.3.1
      - name: update version
        uses: jacobtomlinson/gha-find-replace@a51bbcd94d000df9ca0fcb54ec8be69aad8374b0 # v3.0.2
        with:
          find: "extension_version"
          replace: ${{ steps.package-version.outputs.current-version}}
          include: "vss-extension.json"
      - name: update extension id
        uses: jacobtomlinson/gha-find-replace@a51bbcd94d000df9ca0fcb54ec8be69aad8374b0 # v3.0.2
        with:
          find: "extension_id"
          replace: ${{ secrets.EXTENSION_PROD_ID }}
          include: "vss-extension.json"
      - name: update extension publisher
        uses: jacobtomlinson/gha-find-replace@a51bbcd94d000df9ca0fcb54ec8be69aad8374b0 # v3.0.2
        with:
          find: "extension_publisher"
          replace: ${{ secrets.EXTENSION_PROD_PUBLISHER }}
          include: "vss-extension.json"
      - name: update extension public
        uses: jacobtomlinson/gha-find-replace@a51bbcd94d000df9ca0fcb54ec8be69aad8374b0 # v3.0.2
        with:
          find: "extension_public"
          replace: true
          include: "vss-extension.json"
      - name: update task id
        uses: jacobtomlinson/gha-find-replace@a51bbcd94d000df9ca0fcb54ec8be69aad8374b0 # v3.0.2
        with:
          find: "task_id"
          replace: ${{ secrets.TASK_PROD_ID }}
          include: "goreleaserTask/task.json"
      - run: npm run create
      - name: Upload azure devops extension to marketplace
        run: |
          export VERSION=${{ steps.package-version.outputs.current-version}}
          npm run publish_ci
        env:
          AZURE_DEVOPS_EXT_PAT: ${{ secrets.AZURE_DEVOPS_EXT_PAT }}
          PUBLISHER_NAME: ${{ secrets.EXTENSION_PROD_PUBLISHER }}
          EXTENSION_ID: ${{ secrets.EXTENSION_PROD_ID }}
      - name: Upload azure devops extension to release
        if: always()
        uses: svenstaro/upload-release-action@04733e069f2d7f7f0b4aebc4fbdbce8613b03ccd # v2.9.0
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          file: dist/*
          file_glob: true
          overwrite: true
          tag: ${{ github.ref }}
      - run: git fetch origin main
        if: always()
      - name: 'Automated Version Bump of package.json'
        if: always()
        uses: phips28/gh-action-bump-version@d84ee862bf54f45e75b2918b2ce1007d3fed25f1 # v11.0.0
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          skip-tag: 'true'
          target-branch: 'main'
