name: Build Binary

on:
  push:
    branches:
      - '*'
    tags:
      - '*'
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: '17'
          cache: 'npm'
          cache-dependency-path: package-lock.json
      - run: npm install
      - run: npm run compile
  release:
    needs: build
    runs-on: ubuntu-latest
    if: success() && startsWith(github.ref, 'refs/tags/')
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: '17'
          cache: 'npm'
          cache-dependency-path: package-lock.json
      - run: npm install
      - run: npm run publish
      - uses: ncipollo/release-action@v1
        with:
          artifacts: "dist/*"
          removeArtifacts: true
          token: ${{ secrets.GITHUB_TOKEN }}