name: Build Binary

on:
  push:
    branches:
      - '*'
    tags:
      - '*'
  pull_request:

env:
  PUBLISHER_NAME: GoReleaser
  EXTENSION_ID: goreleaser
  AZURE_DEVOPS_EXT_PAT: ${{ secrets.AZURE_DEVOPS_EXT_PAT }}

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: '17'
          cache: 'npm'
          cache-dependency-path: package-lock.json
      - run: npm install
      - run: npm run compile
  release:
    needs: build
    runs-on: ubuntu-latest
    if: success() && startsWith(github.ref, 'refs/tags/')
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: '17'
          cache: 'npm'
          cache-dependency-path: package-lock.json
      - run: npm install
      - run: git fetch origin main
      - name: 'Automated Version Bump of package.json'
        uses: phips28/gh-action-bump-version@master
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          skip-tag: 'true'
          target-branch: 'main'
      - name: get-npm-version
        id: package-version
        uses: martinbeentjes/npm-get-version-action@master
      - name: update version
        uses: jacobtomlinson/gha-find-replace@v2
        with:
          find: "extension_version"
          replace: ${{ steps.package-version.outputs.current-version}}
          include: "vss-extension.json"
      - run: npm run create
      - name: Upload azure devops extension to marketplace
        run: |
          export VERSION=${{ steps.package-version.outputs.current-version}}
          npm run publish_ci
      - name: Upload azure devops extension to release
        uses: svenstaro/upload-release-action@v2
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          file: dist/*
          file_glob: true
          overwrite: true
          tag: ${{ github.ref }}